lsi: false
safe: true
source: https://github.com/dm319/dm319.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
